### ISSUE TITLE
Add missing tasks fields

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#288] opened 2024-10-17 12:07 UTC
The `src/endpoints/get_tasks.rs` route is not returning the following fields:
- calls
- contracts
- api_url
- regex

So they are not rendered in the admin dashboard.
Please edit the mongo aggregation so that they are returned by this route.

**Comment by ShantelPeters** [comment] 2024-10-17 12:08
Hi @Marchand-Nicolas let me work on this

**Comment by mubarak23** [comment] 2024-10-17 12:08
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am an Experience Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.

### How I plan on tackling this issue
i will update the project section of the MongoDB aggregator with below

```
    doc! {
        "$project": {
            "_id": 0,
            "id": 1,
            "quest_id": 1,
            "name": 1,
            "href": 1,
            "cta": 1,
            "verify_endpoint": 1,
            "verify_redirect" : 1,
            "verify_endpoint_type": 1,
            "desc": 1,
            "completed": { "$gt": [ { "$size": "$completed" }, 0 ] },
            "quiz_name": 1,
            "calls": 1,           
            "contracts": 1,         
            "api_url": 1,           
            "regex": 1              
        }
    },
```

The $project stage now includes the additional fields: calls, contracts, api_url, and regex.

These fields will now be part of the returned documents if they exist in the tasks collection in MongoDB.

**ETH: 4hrs**

@Marchand-Nicolas

**Comment by PoulavBhowmick03** [comment] 2024-10-17 12:09
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue

I will add the following fields to the $project stage:
- calls
- contracts
- api_url
- regex
This will ensure these fields are available in the final response and rendered in the admin dashboard.



I can solve this issue in 1 day

**Comment by 0xdevcollins** [comment] 2024-10-17 12:13
Can I be assigned this issue? I will make a PR with 24hrs

**Comment by sajalbnl** [comment] 2024-10-17 12:13
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by JoE11-y** [comment] 2024-10-17 12:13
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
With over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

**Comment by Benjtalkshow** [comment] 2024-10-17 12:31
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Can this task be assigned to me. I will fix it with ease. I use rust confidently and i am confident i can fix this issue. Thanks

**Comment by GideonBature** [comment] 2024-10-17 12:53
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a software engineer proficient in Rust. I have an understanding of working with api endpoints as well as building them using Rust.

### How I plan on tackling this issue
1. Look at the code in the file to see why those fields are not being returned despite they being in the mongodb.
2. Possibly as stated, I will edit the mongo aggregation and include those fields as part of what will be returned by the get_tasks route.
3. I will then test (if I can get access to it) it to make sure it is working.

**Comment by fishseabowl** [comment] 2024-10-17 14:22
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a blockchain full-stack developer and have contributed to numerous open-source projects, including StarkNet.quest.

### How I plan on tackling this issue
Based on the comments, I would edit the mongo aggregation to return these fields. I believe it should be completed in about a couple of hours.

**Comment by JosueBrenes** [comment] 2024-10-17 15:26
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member.

I estimate this will take 1 day to complete.

### How I plan on tackling this issue
**Update the Aggregation Pipeline**

I will ensure that the get_tasks.rs file correctly projects the fields (calls, contracts, api_url, and regex) in the $project stage of the MongoDB aggregation pipeline.

```jsx
{
   "calls": 1,
   "contracts": 1,
   "api_url": 1,
   "regex": 1
}
```

**Testing and Validation**

After the update, run tests to verify that these fields are correctly returned in the API response.

**Comment by joeperpetua** [comment] 2024-10-17 15:49
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
3+ years doing full stack dev

**Comment by zleypner** [comment] 2024-10-17 16:16
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
  

### How I plan on tackling this issue
3+ years Front End developer experience

**Comment by anonfedora** [comment] 2024-10-18 12:23
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Fullstack Blockchain developer, 
 - Have worked with MySQL, MongoDB and others, know how to optimize queries and data models.
 - Have implemented multiple APIs that require efficient data handling. This ensures that i know how to troubleshoot missing fields in API responses and design routes

### How I plan on tackling this issue
Analyze the Route and Aggregation Logic

Since the get_tasks.rs route is using a MongoDB aggregation, the issue is likely that:
 -   The fields are not being selected or projected properly.
 -   Some stages might filter out relevant documents, causing fields like calls, contracts, api_url, and regex to be absent.
Delivery, 5 hours max

**Comment by Akshola00** [comment] 2024-10-19 11:58
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have extensive experience in backend development, particularly with  MongoDB. My expertise includes designing and optimizing RESTful APIs and working with data aggregation, ensuring that API responses meet frontend requirements.

### How I plan on tackling this issue
Adjust the query to include any missing fields by modifying or adding stages.
Verify that the endpoint returns all required fields and assess data integrity and query performance.
Update documentation to reflect modifications made to the aggregation pipeline and API output structure.

**Comment by emmz3230** [comment] 2024-10-23 01:12
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

i got my first github badge by contributing

### How I plan on tackling this issue
1. understanding codebase
2. check what is wrong with the data and routing pass that is not display like the function or file location or data provided

**Comment by 0xDeon** [comment] 2024-10-24 08:11
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hell, I’m Deon, I am Full-Stack web3 developer and also a previous contributor to Starknet Quest repos. 

I have significant experience in the Backend track as well building applications with Rust and Solidity. I have ample experience and understanding of MongoDB and RESTful API designs, and I'm eager to contribute to this project if given the opportunity.

### How I plan on tackling this issue
- I will begin by reviewing and examining the get_tasks.rs file to understand the current MongoDB aggregation logic and how the data is being fetched.

- I will then determine where to modify the aggregation pipeline to include the fields: calls, contracts, api_url, and regex.

- To implement the fix, I’ll update the MongoDB aggregation to ensure these fields are retrieved and returned in the response.

- Then I will test and verify that the updated route returns the correct data by running tests and checking the API response data.

- Again I believe that good and clean documentation is really necessary in any open source project. In the spirit of that, I’ll update any relevant documentation to reflect the changes made to the endpoint.

I’m super excited to help enhance the backend functionality. Thank you for considering my application! Hve a good day.

**Comment by suhas-sensei** [comment] 2024-10-24 10:09
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
i have experience in cairo and blockchain previously as personal projects and OS, so hoping to make use of them here and mark my first odhack contribution.

### How I plan on tackling this issue
I will optimize the MongoDB aggregation by implementing a dynamic field projection sys that automatically includes call related fields (calls, contracts, api_url, regex) based on task type, while addingg field existence validation in the pipeline to ensure data consistencyy across the admin dashboard, all through a single, efficient $project stage modification.

**Comment by saimeunt** [comment] 2024-10-24 11:07
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm a senior Full Stack Web3 Developer having contributed to several OD Hacks in the past.

### How I plan on tackling this issue
I will fix the route as described in the issue which is pretty self-explanatory.

**Comment by aniruddhaaps** [comment] 2024-10-24 12:07
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Comment by suhas-sensei** [comment] 2024-10-24 15:40
Thank you @Marchand-Nicolas, starting right away.

**Closed as completed** 2024-10-28 12:42 UTC
Labels: 🚨 Small bug, Good first issue, open for contribution, ODHack14
