### ISSUE TITLE
Fix create_quiz route

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#290] opened 2024-10-20 11:49 UTC
In `src/endpoints/admin/quiz/create_quiz.rs` the  `verify_endpoint` field should be "quests/verify_quiz" instead of "/quests/verify_quiz" (just remove the `/` at the begining)

**Comment by NueloSE** [comment] 2024-10-20 11:54
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am Expirenced using cairo kind of similar to rust kindly assign me

### How I plan on tackling this issue
I will locate and update the file as requested and ensures it works fine b4 making a PR

**Comment by GideonBature** [comment] 2024-10-20 11:59
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
my name is Gideon Bature, quite proficient with Rust and other programming languages like TypeScript and JavaScript. I have once contributed to Starknet quest project during the last ODHack.

### How I plan on tackling this issue
I will do as asked in the description, to remove the leading '/' in the '/quests/verify_quiz' so that it becomes just 'quests/verify_quiz' in the 'src/endpoints/admin/quiz/create_quiz.rs' codebase.

**Comment by anonfedora** [comment] 2024-10-20 14:45
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
A full stack Blockchain developer 

### How I plan on tackling this issue
Assign me, willing to work

**Comment by pheobeayo** [comment] 2024-10-20 14:59
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.

### How I plan on tackling this issue
My Approach includes:
- Reviewing of the file where the route is implemented.
- fix the routing as instructed.
- Create a Pull Request (PR)
- Request for a Review.
- Make changes based on the Review of the PR.

**Comment by Gerson2102** [comment] 2024-10-21 03:27
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other Rust/Cairo projects like:

- `kakarot-rpc`
- `ef-tests`
- `Madara`
- `Raito`
- `Starknet Phone`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### How I plan on tackling this issue
### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by emmz3230** [comment] 2024-10-23 01:10
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

i got my first github badge by contributing

### How I plan on tackling this issue
1.readint the codebase
2.fix the routing in the app.js or main.js file to the proper file location

**Comment by ryzen-xp** [comment] 2024-10-23 19:03
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Blockchain developer with experience in Rust ,solidity , Cairo , JavaScript and TypeScript.

### How I plan on tackling this issue
already  created PR( #295 ) Please check and merge  :  https://github.com/lfglabs-dev/api.starknet.quest/pull/295
Please Sir/mam

**Comment by meetjn** [comment] 2024-10-23 20:30
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a blockchain developer intern at Quranium, skilled in Rust and solidity. And have been contributing to the open source projects from the start of this year.

### How I plan on tackling this issue
I would approach this problem by going to the desired source code file 'verify_endpoint' and removing a '/' from the "/quests/verify_quiz" making it into "quests/verify_quiz"

**Comment by PoulavBhowmick03** [comment] 2024-10-24 07:08
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.


### How I plan on tackling this issue
The task is straightforward: i will update the `verify_endpoint` field by removing the leading `/` in the `create_quiz` route. This will ensure that the `verify_endpoint` field is correctly formatted as `"quests/verify_quiz"` instead of `"/quests/verify_quiz"`.

1. **Locate the `verify_endpoint` Assignment:**
   In the `create_quiz` route, the current assignment for the `verify_endpoint` field is:
   ```rust
   verify_endpoint: "/quests/verify_quiz".to_string(),
   ```
   The issue is that the `/` at the beginning is unnecessary.

2. **Update the `verify_endpoint` Field:**
   I will simply remove the `/` so that the field is updated to:
   ```rust
   verify_endpoint: "quests/verify_quiz".to_string(),
   ```

**Comment by martinvibes** [comment] 2024-10-24 07:13
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

**Comment by mamicho16** [comment] 2024-10-24 07:30
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
As a software developer with experience in web development, my background directly aligns with this endpoint configuration issue. My relevant experience includes:
Strong backend development skills: I'm proficient in API development and route management, with particular experience in RESTful services and endpoint configuration.
Endpoint architecture expertise: I have experience working with routing systems and URL path management in web applications. This includes implementing endpoint configurations across different frameworks.

### How I plan on tackling this issue
Review and analyze the current endpoint configuration in src/endpoints/admin/quiz/create_quiz.rs
Make the required modification by changing the verify_endpoint field, removing the first '/' from '/quests/verify_quiz'
Run comprehensive tests to ensure the change doesn't affect other functionalities
Create a pull request with detailed documentation of the changes

**Comment by mariocodecr** [comment] 2024-10-24 07:50
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.

### How I plan on tackling this issue
I will open the src/endpoints/admin/quiz/create_quiz.rs file and locate the verify_endpoint field. Update the value by removing the leading /, so it becomes "quests/verify_quiz" instead of "/quests/verify_quiz". After making this change, ensure that any affected logic or routes are still functioning properly by running tests or verifying manually. Finally, commit the change, making sure that everything works as expected.

**Comment by vijay-kesanakurthi** [comment] 2024-10-24 10:49
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am fullstack developer. I'd like to work on this issue, this is my first contribution to starknet, Could you please assign it to me?

### How I plan on tackling this issue
Change the endpoint to "/quests/verify_quiz" to "quests/verify_quiz"

**Comment by 0xdevcollins** [comment] 2024-10-24 11:53
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. 

### How I plan on tackling this issue
To update the verify_endpoint field in src/endpoints/admin/quiz/create_quiz.rs, I will locate the line where this field is defined. I will then remove the leading slash from the string so that it reads "quests/verify_quiz" instead of "/quests/verify_quiz".

This change is important because the leading slash can affect how the endpoint is resolved within the routing logic of the application. By ensuring the verify_endpoint is correctly formatted, I will help maintain consistent and accurate routing behavior for the quiz verification process.

After making this modification, I will review the surrounding code to ensure that no other related changes are necessary. Finally, I will test the relevant functionality to verify that the update works as intended and that the quiz verification process remains seamless.

**Comment by aniruddhaaps** [comment] 2024-10-24 12:07
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Comment by SudiptaPaul-31** [comment] 2024-10-24 13:13
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello! I’m Sudipta Paul, and I currently have 1.5 years of experience in blockchain and web development. I’m excited to contribute to this issue regarding fixing the create_quiz route.

### How I plan on tackling this issue
The problem is that in src/endpoints/admin/quiz/create_quiz.rs, the verify_endpoint field has an extra forward slash (/) at the beginning ("/quests/verify_quiz"). This results in an incorrect API route. The solution is to remove the leading slash so the field reads "quests/verify_quiz" instead of "/quests/verify_quiz". This minor change ensures that the route works as intended without the slash disrupting the path.

**Closed as completed** 2024-10-26 11:04 UTC
Labels: 🚨 Small bug, Good first issue, open for contribution, ODHack14
