### ISSUE TITLE
Fix create_boost.rs

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#287] opened 2024-10-17 11:59 UTC
In `src/endpoints/admin/quest_boost/create_boost.rs`, line 38, the collection should be "tasks" and not "quests". (Because we already get the quests collection on the upper line).

**Comment by ShantelPeters** [comment] 2024-10-17 12:00
Hi @Marchand-Nicolas can i please be assigned to this issue?

**Comment by mubarak23** [comment] 2024-10-17 12:00
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi 
I am an Experience Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.


### How I plan on tackling this issue
CHANGE this 

`let insert_collection = state.db.collection::<QuestTaskDocument>("quests");`

to this 

`let insert_collection = state.db.collection::<QuestTaskDocument>("tasks"); `

**ETH: 1hour**

@Marchand-Nicolas

**Comment by PoulavBhowmick03** [comment] 2024-10-17 12:01
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
I have a good experience of the Starknet quest api repository and have made previous contribution
I can fix this issue by changing the collection to 'tasks instead of quests'

```
let insert_collection = state.db.collection::<QuestTaskDocument>("quests");
````
I will change it to
```
let insert_collection = state.db.collection::<QuestTaskDocument>("tasks");
```

ETA- 1 day

**Comment by sajalbnl** [comment] 2024-10-17 12:03
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by Benjtalkshow** [comment] 2024-10-17 12:07
@Marchand-Nicolas 
Can I be assigned to this task? I will quickly fix this bug. My ETA is 24hrs. Thanks

**Comment by 0xdevcollins** [comment] 2024-10-17 12:12
Can I be assigned this issue? I will make a PR within 24hrs

**Comment by fishseabowl** [comment] 2024-10-17 14:24
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a blockchain full-stack developer and have contributed to numerous open-source projects, including StarkNet.quest.

### How I plan on tackling this issue
Based on the comments, II will update line 38 and the related code, then run tests on the changes. I believe it should be completed in about a hour.

**Comment by JosueBrenes** [comment] 2024-10-17 15:23
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member.

I estimate this will take 1 day to complete.

### How I plan on tackling this issue
**Update the collection reference**

The issue occurs because the code mistakenly references the wrong collection ("quests") in create_boost.rs. I will modify the collection reference to "tasks" to match the intended behavior.

  ```jsx
  let insert_collection = state.db.collection::<QuestTaskDocument>("tasks");  
  ```

**Run tests and validation**

I will run the appropriate tests to ensure the fix works as expected and that the correct collection is used in all relevant operations.

**Comment by joeperpetua** [comment] 2024-10-17 15:49
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
3+ years doing full stack dev

**Comment by zleypner** [comment] 2024-10-17 16:15
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
 

### How I plan on tackling this issue
3+ years Front End developer experience

**Comment by Gerson2102** [comment] 2024-10-21 03:24
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other Rust based projects like:

- `kakarot-rpc`
- `ef-tests`
- `Madara`
- `Raito`
- `Starknet Phone`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### How I plan on tackling this issue
### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

I will change this on the base code:

```rust
let insert_collection = state.db.collection::<QuestTaskDocument>("quests");
```

to this:

```rust
let insert_collection = state.db.collection::<QuestTaskDocument>("tasks");
```
---

**Comment by emmz3230** [comment] 2024-10-23 01:25
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

### How I plan on tackling this issue

i will love to use my skill to change the collection from task to quests

**Comment by ryzen-xp** [comment] 2024-10-23 19:16
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Blockchain developer with experience in Rust ,solidity , Cairo , JavaScript and TypeScript.



### How I plan on tackling this issue
Pull Request Created at #296 
Please Sir , Assign me and then  check and merge

**Comment by 0xDeon** [comment] 2024-10-24 08:09
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello, I’m Deon, I am Full-Stack web3 developer and also a previous contributor to Starknet Quest repos. I have significant experience in the Backend track as well building applications with Rust and Solidity. 

I have ample experience and understanding of MongoDB and RESTful API designs, and I'm eager to contribute to this project if given the opportunity.

### How I plan on tackling this issue
- Firstly I will review the code, and examine the create_boost.rs file, specifically line 38, to understand the context of the current collection name.

- I will then update the collection name from "quests" to "tasks" to ensure the correct data is referenced.

- After updating the name, I’ll run tests to confirm that the change works as expected and that data is properly handled.

- On the off chance that there might be some side effects to my updated changes, I’ll ensure that my modifications don't affect other parts of the application and the whole application works as expected.

- Finally I’ll update any relevant comments or documentation to reflect the changes whilel keeping the code clean and well structured.

I’m looking forward to working on this backend issue. Thank you for considering my application! GGs

**Comment by zleypner** [comment] 2024-10-24 08:12
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
 continue making contribution to this project and contribute to the project's success.
I'm also a member of the Dojo Coding community CR.


### How I plan on tackling this issue

I will modify the get_tasks.rs file regarding the following fields  calls, contracts, api_url, and regex; within the $project stage of the MongoDB aggregation pipeline.

Once the changes  have been made, I will test properly.

**Comment by suhas-sensei** [comment] 2024-10-24 10:06
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
i have experience in cairo and blockchain previously as personal projects and OS, so hoping to make use of them here and mark my first odhack contribution.

### How I plan on tackling this issue
I'll modify the MongoDB collection reference by implementing a query optimization that avoids the redundant quests collection access, swapping state.db.collection::<QuestTaskDocument>("quests") to state.db.collection::<QuestTaskDocument>("tasks") while adding a validation check to ensure we're not accidentally querying the same collection twice during the boost creation process.

**Comment by saimeunt** [comment] 2024-10-24 11:08
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm a senior Full Stack Web3 Developer having contributed to several OD Hacks in the past.

### How I plan on tackling this issue
I will fix the route as described in the issue which is pretty self-explanatory.

**Comment by 0xdevcollins** [comment] 2024-10-24 11:55
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. 

### How I plan on tackling this issue
To correct the collection name in `src/endpoints/admin/quest_boost/create_boost.rs`, I will navigate to line 38 where the collection is defined. I will change the collection name from `"quests"` to `"tasks"` to ensure that the correct data is being referenced.

This adjustment is necessary because the preceding code already retrieves the quests collection, and the intention here is to interact with the tasks collection. By updating this line, I will help prevent potential errors in data retrieval or manipulation, ensuring that the application functions correctly.

After making this change, I will review the surrounding code to confirm that everything aligns with the intended functionality. Finally, I will run tests to verify that the modification does not introduce any issues and that the boost creation process operates as expected with the correct collection.

**Comment by aniruddhaaps** [comment] 2024-10-24 12:07
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Comment by GideonBature** [comment] 2024-10-24 12:51
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
My name is Gideon Bature, a Software Engineer with proficiency in Rust. I have contributed to open-source projects, both in and outside of the only dust platform. I participated in the previous ODhack and was able to worked on an issue assigned to me on this very starknet quest. 

### How I plan on tackling this issue
Just as described, I will in the `src/endpoints/admin/quest_boost/create_boost.rs` on line 38 change the collection from `quests` to `tasks`.

**Comment by ryzen-xp** [comment] 2024-10-24 14:17
PR: https://github.com/lfglabs-dev/api.starknet.quest/pull/297

**Closed as completed** 2024-10-26 10:07 UTC
Labels: 🚨 Small bug, Good first issue, open for contribution, ODHack14
